const express = require('express');
const { protect } = require('../middleware/auth');

const router = express.Router();
router.use(protect);

// POST /api/openai/analyze
router.post('/analyze', async (req, res, next) => {
  try {
    const { text } = req.body;
    if (!text || text.length < 50) {
      return res.status(400).json({ error: 'Text must be at least 50 characters.' });
    }
    if (!process.env.OPENAI_API_KEY) {
      return res.status(503).json({ error: 'OpenAI API key not configured.' });
    }

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [
          {
            role: 'system',
            content: `You are an expert at detecting whether text was written by a human or generated by AI. Analyze the given text and respond ONLY with a JSON object in this exact format with no extra text:
{"score":<0-100 where 100=definitely human>,"verdict":"<likely_human|uncertain|likely_ai_assisted|likely_ai>","confidence":<0-100>,"signals":["signal1","signal2","signal3"],"summary":"<one sentence>"}`
          },
          {
            role: 'user',
            content: `Analyze this text:\n\n${text.slice(0, 2000)}`
          }
        ],
        temperature: 0.1,
        max_tokens: 300
      })
    });

    const data = await response.json();
    if (!response.ok) throw new Error(data.error?.message || 'OpenAI API error');

    const content = data.choices[0]?.message?.content;
    let analysis;
    try {
      analysis = JSON.parse(content);
    } catch {
      return res.status(500).json({ error: 'Failed to parse OpenAI response.' });
    }

    res.json({ analysis, model: 'gpt-3.5-turbo' });
  } catch (error) {
    next(error);
  }
});

module.exports = router;
